# Database IP will be written in place of localhost when working in an office/company
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb

# When working with production databases, username & password are required
#spring.data.mongodb.username=username
#spring.data.mongodb.password=password
